ALTER TYPE "RecheckStatus" ADD VALUE IF NOT EXISTS 'PASSED';
ALTER TYPE "RecheckStatus" ADD VALUE IF NOT EXISTS 'SUSPICIOUS';
ALTER TYPE "RecheckStatus" ADD VALUE IF NOT EXISTS 'FAILED';

ALTER TABLE "EventRecheck" ADD COLUMN "submittedAt" TIMESTAMP(3);
